name: Angular-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
      # Setup nodeJS 
      - name: Setup Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "22"

      # Install dependencies
      - name: Install deps
        run: npm i

      - name: Inject env vars
        run: |
          sed -e "s|\${GEMINI_API_KEY}|${{ secrets.GEMINI_API_KEY || '' }}|g" \
          src/environment/environment.ts > \
          src/environment/environment.prod.ts

      # Build app for production
      - name: Build app bundle
        run: npm run build -configuration=production

      # Deploy to Github pages
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          build_dir: dist/My-Notion
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

        
